title: Luis Alfonso Pérez Mijangos # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  Este portafolio de proyectos presenta una selección de mis trabajos más destacados como estudiante de Ingeniería en Robótica y Sistemas Digitales en el Tecnológico de Monterrey. 
  Los proyectos incluyen investigaciones en robótica autónoma, diseño de sistemas digitales, programación de microcontroladores y más, todos ellos desarrollados con el objetivo de demostrar mi capacidad para crear soluciones innovadoras y prácticas en diferentes áreas de aplicación. 
  Espero que este portafolio brinde una visión completa de mi experiencia y habilidades técnicas como futuro ingeniero.  
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
